phrase:
  project_id: 2b9e520da3892c491cd21b2283e91ab9
  file_format: yml
  push:
    sources:
    - file: ./config/.yml
      params:
        file_format: yml
  pull:
    targets:
    - file: ./config/;.yml
      params:
        file_format: yml
